[package]
name = "enlil-async"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures = "0.3.31"
iced = { version = "0.12", features = ["tokio","advanced"] }
tokio = { version = "1", features = ["full"] }
