[package]
name = "eframe_template"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30"
egui = "0.30"
rand = "0.8"
chrono = "0.4"
epaint = "0.22"  # Для дополнительных возможностей стилизации
